name: Update Jobs, Rentals and Directory

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Update jobs
        run: |
          python jobs/fetch_jobs.py
          
      - name: Update rentals
        run: |
          python rentals/fetch_rentals.py
          
      - name: Update directory
        run: |
          python directory/fetch_companies.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add jobs/latest_jobs.json rentals/latest_rentals.json directory/companies.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour automatique des offres et de l'annuaire - $(date)" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
